### ISSUE TITLE
Underscore(_) 겹침 현상

### ISSUE THREAD

**Issue by Park-Joonyoung** [sogang-icpc-team/sogang-icpc-team.github.io#67]
![underscore](https://github.com/user-attachments/assets/9a16c8c4-04d9-4ed9-abc0-a6365111d3b2)
위 사진과 같이 underscore가 다른 글자와 겹치는 이슈가 있습니다.

**Comment by shiftpsh** [comment]
적당히 고쳐 뒀습니다
