### ISSUE TITLE
SCPC 2024 정보 추가

### ISSUE THREAD

**Issue by shiftpsh** [sogang-icpc-team/sogang-icpc-team.github.io#70]
올해 누가 출전했는지 모르겠습니다

**Comment by dong-gas** [comment]
파이널 진출자입니다.
박수현 (shitpsh, 4등상)
강효규 (djs100201, 5등상)
박성준 (greedev, 5등상)
김동건 (dong_gas)
조원빈 (wbcho0504)
송근수 (hulahula3247)
채성우 (lem0nad3)
